version: "3.8"
services: 
  app:
    build: .
    volumes:
      - .:/immflytest
    ports:
      - 8000:8000
    image: app:django
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db: # Local db
    image: postgres
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres-db
