# Generated by Django 3.2.18 on 2023-03-20 18:35

from django.db import migrations, models
import django.db.models.deletion
import tree.fields
import tree.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.IntegerField(default=1)),
                ('path', tree.fields.PathField(order_by=('position', 'name'))),
                ('public', models.BooleanField(default=False)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.channel')),
            ],
            options={
                'ordering': ('path',),
            },
            bases=(models.Model, tree.models.TreeModelMixin),
        ),
    ]
