# Generated by Django 3.2.18 on 2023-03-22 16:09

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.CharField(default='ZZ', max_length=2, validators=[django.core.validators.RegexValidator(message='Not a valid language', regex='^[A-Z]{2}$')]),
        ),
        migrations.AddField(
            model_name='channel',
            name='picture',
            field=models.ImageField(default='placeholder.png', storage=django.core.files.storage.FileSystemStorage(location='/media/channel_photo'), upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
