# Generated by Django 3.2.18 on 2023-03-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='content',
        ),
    ]
