# Generated by Django 3.2.18 on 2023-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_content_channel'),
        ('channels', '0005_remove_channel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='channel', to='content.Content'),
        ),
    ]
