# Generated by Django 3.2.18 on 2023-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(default='Unknown author', max_length=30),
        ),
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default='Without description', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.CharField(default='Unknown genre', max_length=30),
        ),
    ]
