# Generated by Django 3.2.18 on 2023-03-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_remove_channel_content'),
        ('content', '0003_alter_content_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='channels.channel'),
        ),
    ]
